version: '3'

services:
  tic-tac-toe-app:
    container_name: tic-tac-toe-app
    image: web-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:80"
    restart: unless-stopped
  
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: tic_tac_toe_user
      POSTGRES_PASSWORD: t1ct4ct0e
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - postgres
  
networks:
  postgres:
    driver: bridge
  
volumes:
  postgres:
